# Generated by Django 5.0.1 on 2024-01-11 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idMedico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('edad', models.PositiveSmallIntegerField()),
                ('foto_perfil', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('actividad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('edad', models.PositiveSmallIntegerField()),
                ('foto_perfil', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, verbose_name='')),
                ('medicamento', models.CharField(max_length=50)),
                ('alergia', models.CharField(max_length=50)),
                ('actividad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('costo', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('idMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medico')),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente')),
            ],
        ),
    ]
